[package]
name = "mister"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = [ "staticlib" ] # to generate a `lib<package_name>.a`
path = "src/lib.rs"

[[bin]]
name = "mister"
path = "src/main.rs"

[profile.release]
lto = true
panic = "abort"
overflow-checks = false
strip = "debuginfo"

[dependencies]
bitvec = "1.0.1"
chrono = "0.4.26"
clap = { version = "4.3.5", features = ["derive"] }
clap-verbosity-flag = "2.0.1"
core_affinity = "0.8.0"
embedded-fps = { version = "0.1.0", features = ["std"] }
embedded-graphics = "0.8.0"
embedded-graphics-simulator = { git = "https://github.com/hansl/embedded-graphics-simulator.git", rev = "e33d171d3f38a242e5cb6a85f6dc36b8e689f403", default-features = false }
embedded-graphics-transform = "0.1.0"
embedded-iconoir = "0.2.1"
embedded-layout = "0.3.1"
hex = "0.4.3"
json5 = "0.4.1"
libc = { version = "*", default-features = false }
libc-print = "0.1.21"
merge = { git = "https://github.com/hansl/merge-rs.git", rev = "ef451941cf3faefc8b6514fa2fb9105f823e6d60", features = ["num", "derive"] }
num-traits = "0.2.15"
serde = { version = "1.0.164", features = ["derive"] }
serde-hex = "0.1.0"
serde_json = "1.0.64"
serde_with = { version = "3.0.0", features = ["hex"] }
softbuffer = "0.3.0"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.40"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["tracing-log"] }
validator = { version = "0.16.1", features = ["derive"] }

[dev-dependencies]
tempdir = "0.3.7"
test-generator = "0.3.1"

[features]
default = ["platform_desktop"]
platform_de10 = []
platform_desktop = ["embedded-graphics-simulator/with-sdl"]
