[workspace]
members = [
    "cyclone-v",
    "de10-nano",
    "golem-db",
    "golem",
    "junior",
    "mister-fpga",
    "senior",
]
resolver = "2"

[profile.release]
lto = true
overflow-checks = false
panic = "abort"
strip = true
debug = false

[profile.dev]
debug = 0
