[workspace]
members = [
    "cyclone_v",
    "golem-db",
    "golem",
    "mister-fpga",
]
resolver = "2"

[profile.release]
lto = "fat"
incremental = false
overflow-checks = false
panic = "abort"
strip = "symbols"
