[package]
name = "mister"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = [ "staticlib" ] # to generate a `lib<package_name>.a`
path = "src/lib.rs"

[[bin]]
name = "mister"
path = "src/main.rs"

[profile.release]
lto = true
panic = "abort"
overflow-checks = false
strip = "debuginfo"

[dependencies]
alkahest = "0.3.0"
bitvec = "1.0.1"
cfg-if = "1.0.0"
chrono = "0.4.26"
clap = { version = "4.3.5", features = ["derive"] }
clap-verbosity-flag = "2.0.1"
core_affinity = "0.8.0"
embedded-graphics = "0.8.0"
embedded-graphics-transform = "0.1.0"
embedded-iconoir = { git = "https://github.com/hansl/embedded-iconoir.git", branch = "add-16px", default-features = false, features = ["16px"] }
embedded-layout = "0.3.1"
embedded-menu = "0.2.0"
hex = "0.4.3"
image = "0.24.6"
json5 = "0.4.1"
libc = { version = "*", default-features = false }
merge = { git = "https://github.com/hansl/merge-rs.git", rev = "ef451941cf3faefc8b6514fa2fb9105f823e6d60", features = ["num", "derive"] }
network-interface = "1.0.1"
num-traits = "0.2.15"
ouroboros = "0.17.0"
sdl3 = "0.4.0"
serde = { version = "1.0.164", features = ["derive"] }
serde-hex = "0.1.0"
serde_json = "1.0.64"
serde_with = { version = "3.0.0", features = ["hex"] }
static_assertions = "1.1.0"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.40"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["tracing-log"] }
validator = { version = "0.16.1", features = ["derive"] }

[dev-dependencies]
tempdir = "0.3.7"
test-generator = "0.3.1"

[features]
default = ["platform_desktop"]
# Support for the DE10-Nano board.
platform_de10 = []
# Support for a desktop simulator.
platform_desktop = []
