[package]
name = "mister"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = [ "staticlib" ] # to generate a `lib<package_name>.a`

[dependencies]
clap = { version = "4.3.5", features = ["derive"] }
libc = { version = "*", default-features = false }
libc-print = "0.1.21"
strum = { version = "0.25.0", features = ["derive"] }

[profile.dev]
panic = "abort"
overflow-checks = false

[profile.release]
lto = true
panic = "abort"
overflow-checks = false
strip = "debuginfo"
