[workspace]
members = [
    "bk2-format",
    "cyclone-v",
    "de10-nano",
    "fce-movie-format",
    "golem",
    "golem-core",
    "golem-db",
    "junior",
    "mister-fpga",
    "superscope",
    "senior",
]
resolver = "2"

[profile.release]
lto = true
overflow-checks = false
panic = "abort"
strip = true
debug = false

[profile.dev]
overflow-checks = false
debug = 0
panic = "abort"

