[package]
name = "mister"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = [ "staticlib" ] # to generate a `lib<package_name>.a`

[profile.dev]
panic = "abort"
overflow-checks = false

[profile.release]
lto = true
panic = "abort"
overflow-checks = false
strip = "debuginfo"

[dependencies]
clap = { version = "4.3.5", features = ["derive"] }
clap-verbosity-flag = "2.0.1"
core_affinity = "0.8.0"
libc = { version = "*", default-features = false }
libc-print = "0.1.21"
strum = { version = "0.25.0", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["tracing-log"] }
