[package]
name = "golem-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
image = "0.25.0"
mister-fpga = { path = "../mister-fpga", features = ["sdl"] }
sdl3 = "0.5.0"
