[package]
name = "fce-movie-format"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
encoding = "0.2.33"
hex = "0.4.3"
thiserror.workspace = true
tracing.workspace = true
