#[target.armv7-unknown-linux-gnueabihf]
#rustflags = ["-C", "link-arg=-fuse-ld=lld"]

#[build]
#target = "armv7-unknown-linux-musleabihf"
#[target.armv7-unknown-linux-c]
#linker = "arm-linux-gnueabihf-ld"

#[build]
#target = "arm-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-unknown-linux-gnueabihf-gcc"
