[package]
name = "cyclone-v"
version = "0.1.0"
edition = "2018"
authors = ["Hans Larsen <hans.larsen@gmail.com>"]

[dependencies]
bitfield = "0.14.0"
byteorder = "1.4.3"
libc = "0.2.147"
memoffset = "0.9.0"
paste = "1.0.14"
static_assertions = "1.1.0"

[features]
default = ["std"]
std = []
